#!/bin/bash

#
# DO NOT EDIT THIS FILE
#
# It is automatically copied from https://github.com/pion/.goassets repository.
#
# If you want to update the shared CI config, send a PR to
# https://github.com/pion/.goassets instead of this repository.
#

SCRIPT_PATH=$(
  cd "$(dirname "${BASH_SOURCE[0]}")"
  pwd -P
)

GOASSETS_PATH="${SCRIPT_PATH}/.goassets"

if [ -d "${GOASSETS_PATH}" ]; then
  git -C "${GOASSETS_PATH}" checkout master
  git -C "${GOASSETS_PATH}" pull origin master
else
  git clone --depth=1 https://github.com/pion/.goassets.git "${GOASSETS_PATH}"
fi

cp "${GOASSETS_PATH}/hooks/commit-msg.sh" "${SCRIPT_PATH}/../.git/hooks/commit-msg"
cp "${GOASSETS_PATH}/hooks/pre-commit.sh" "${SCRIPT_PATH}/../.git/hooks/pre-commit"
cp "${GOASSETS_PATH}/hooks/pre-push.sh" "${SCRIPT_PATH}/../.git/hooks/pre-push"
