name: Go Test (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Go Tests on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ~/.cache
          key: ${{ runner.os }}-amd64-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-amd64-go-

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'

      - name: Setup go-acc
        run: go install github.com/ory/go-acc@latest

      - name: Run pre test hook
        run: |
          if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
          if [ -n "${PRE_TEST_HOOK}" ]; then ${PRE_TEST_HOOK}; fi

      - name: Run test
        run: |
          if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi

          set -euo pipefail
          go-acc -o cover.out ./... -- -bench=. -v -race 2>&1 | tee /tmp/gotest.log

      - name: Run post test hook
        run: |
          if [ -f .github/.ci.conf ]; then . .github/.ci.conf; fi
          if [ -n "${POST_TEST_HOOK}" ]; then ${POST_TEST_HOOK}; fi

      - name: Upload test log
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-log-1.25
          path: /tmp/gotest.log
          if-no-files-found: error

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true
          flags: go
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
